### ISSUE TITLE
Unable to upload own Data

### ISSUE THREAD

**Issue by tirichl** [junjiezhujason/aegis#7]
Hi, 
This looks like a great tool and I am looking forward to use it. However, I have not been able to upload my own Data through the Data upload tab, the refresh button doesn't switch to green - even though my data fulfills the required data syntax. I tried the specified sample file "great_srf_example.txt" and it isn't accepted either. The console throws the following error: 

`[01:05:30 main ERROR] Exception on /upload_view_file [POST]
Traceback (most recent call last):
  File "/home/tilma/.local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/tilma/.local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/tilma/.local/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/tilma/.local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/tilma/.local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/tilma/.local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "main.py", line 604, in upload_view_file
    fn = werkzeug.secure_filename(f.filename)
AttributeError: module 'werkzeug' has no attribute 'secure_filename'
[01:05:30 tornado.access ERROR] 500 POST /upload_view_file (::1) 18.84ms
`

I am using bash on Windows 10. Any help is greatly appreciated.

**Comment by junjiezhujason** [comment]
Hi,

I think the data upload issue is probably due to the werkzeug/tornado
dependencies during
the setup. I am not sure if this is related to Windows or not. You can
modify the source code to make the fn variable in upload_view_file your
data path and see if this error goes away.

Please note that this software has only been tested on mac and linux
operating systems, and I am not able to assist with windows-specific
issues.

Jason

**Comment by tirichl** [comment]
Thank you for your answer. I didn't have any sucess with that, however I was able to solve the problem: According to this issue 
(https://github.com/maxcountryman/flask-uploads/pull/28), there is a bug in flask 1.0.0, which caused this error. Downgrading with 
`pip3 install -U Werkzeug==0.16.0` to 0.16.0 did the trick. Thank you for your time!
